name = "sharering-test"
main = "functions/index.js"

[vars]
DB = "DB"
R2_BUCKET_URL = "https://24110c1529bddb6fc66ec15da1c1b9b7.r2.cloudflarestorage.com"
R2_API_TOKEN = "4nE6zX0KOHkmaCzhhJbMjITgJw8oV_Kq-cShkQyJgeS"
CLOUDFLARE_ACCOUNT_ID = "24110c1529bddb6fc66ec15da1c1b9b7"

[[d1_databases]]
binding = "DB"
database_name = "sharering_db"
database_id = "2731a38b-2e18-4d99-a509-f49114e89409"

[[r2_buckets]]
binding = "MY_R2_BUCKET"
bucket_name = "my-photo-bucket"

# ログインおよび新規登録エンドポイントのルーティング設定
[[routes]]
pattern = "https://sharering-test.pages.dev/login"
script = "login-handler"

[[routes]]
pattern = "https://sharering-test.pages.dev/register"
script = "register-handler"
