name = "sharering-test"
main = "worker.js"  # エントリーポイントファイル名が正しいか確認
compatibility_date = "2024-11-02"
account_id = "24110c1529bddb6fc66ec15da1c1b9b7"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "sharering"
database_id = "217563d5-95bd-476b-ae9a-d3e9f0d322cd"
