name = "sharering-test"
main = "/fuctions/index.js"

[vars]
DB = "DB"

[[d1_databases]]
binding = "DB"
database_name = "sharering_db"
database_id = "2731a38b-2e18-4d99-a509-f49114e89409"  # Cloudflare Dashboardで確認できます
